FROM ubuntu:22.04

WORKDIR /libpaseto

SHELL ["/bin/bash", "-c"]

RUN echo "Etc/UTC" > /etc/timezone

RUN apt-get update && \
	DEBIAN_FRONTEND=noninteractive \
	apt-get -y --no-install-recommends install \
		build-essential \
		clang \
		gdb \
		cmake \
		git \
		ca-certificates \
		pkg-config \
		cmake-data \
		llvm \
		libcrypto++-dev \
		libsodium-dev


CMD ["tail", "-f", "/dev/null"]
